### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by mkopljar** [oferwald/transposh#16]
It seems that Wordpress vulnerability database (https://patchstack.com/database/vulnerability/transposh-translation-filter-for-wordpress/wordpress-transposh-wordpress-translation-plugin-1-0-8-1-sensitive-information-disclosure-vulnerability?_a_id=110) found a security issue with this plugin.

Can you advise ?

**Comment by oferwald** [comment]
Yes, upgrade to 1.0.9.x which does not have that issue afaik.

**Comment by oferwald** [comment]
Marking closed
