### ISSUE TITLE
Home page url

### ISSUE THREAD

**Issue by 1formanet** [oferwald/transposh#17]
Hi, When I am on the french homepage, and click on the english flag, the page is not existing :
french : https://lajoieenmain.fr
english flag : https://lajoieenmain.fr/en/

But the traduction exists in an other url : https://lajoieenmain.fr/?lang=en

Thanks

**Comment by oferwald** [comment]
Please disable the option for rewriting urls in the plugin, than it will redirect to the ?lang url

**Comment by 1formanet** [comment]
Hello, thanks for your answer.But this option is already not active :
It is working for all the pages ; except homepage

**************Sylvie 

    Le vendredi 19 janvier 2024 à 15:37:04 UTC+1, Ofer Wald ***@***.***> a écrit :  
 
 


Please disable the option for rewriting urls in the plugin, than it will redirect to the ?lang url

**Comment by 1formanet** [comment]
![Capture d’écran_2024-01-20_15-45-35](https://github.com/oferwald/transposh/assets/155544087/65a5eed4-7173-45a4-998a-671bc993dee1)

**Comment by 1formanet** [comment]
It works ! I did the opposite : ask for activate rewriting urls ;)
